baseurl = "/"
languageCode = "en-us"
title = "A Tidybiology website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

 [[menu.main]]
    name = "Instructional Videos"
    url = "/about/"
[[menu.main]]
    name = "Package"
    url = "/docs/"
[[menu.main]]
    name = "Book"
    url = "/book/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/hirscheylab/tidybiology"
[[menu.main]]
    name = "Quiz"
    url = "https://akshay-bareja.shinyapps.io/Chromosome/#section-scratchpad"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/matthewhirschey"
[[menu.main]]
    name = "YouTube"
    url = "https://www.youtube.com/channel/UCstAS6IpgYgZ9Cvcag_YlCQ"

[params]
    description = "A Tidybiology website." # A brief description of your website. It is not visible on web pages (you can only see it from the HTML source), but should give search engines a hint about your website.

    # options for highlight.js (version, additional languages, and theme)
    # for more info - https://bookdown.org/yihui/blogdown/themes.html
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    # By default, the image logo.png under the static/ directory is used
    url = "tidybiology_hex.png"
    # url = "tidybiology_channel_art.png"
    width = 50
    height = 50
    alt = "Logo"

